version: '2'
services:

  demo:
    # 240*1024*1024 = 251658240 Byte = 240 MB
    mem_limit: 251658240
    build: .
    working_dir: "/demo"
    depends_on:
      - mysql
    ports:
      - 4000:4000
      - 54000:54000
    environment:
      - SERVICE_ENV=local
    volumes:
      - $PWD/package.json:/demo/package.json
      - $PWD/shared:/demo/shared
      - $PWD/config:/demo/config
      - $PWD/app.js:/demo/app.js
      - $PWD/controllers:/demo/controllers
      - $PWD/fittings:/demo/fittings
      - $PWD/swagger:/demo/swagger
      - $PWD/public:/demo/public
      - $PWD/test:/demo/test
      - $PWD/.env:/demo/.env
    command: npm run inspect
    #command: tail -f /var/log/bootstrap.log

  mysql:
    # 512*1024*1024 = 536870912 Byte = 512 MB
    mem_limit: 536870912
    image: mysql:5.6
    ports:
      - 3306:3306
    volumes:
      - $PWD/docker/mysql/data:/var/lib/mysql
    env_file:
      - ./mysql.env
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    networks:
      default:
        aliases:
          - viron.dev